# Generated by Django 4.1.4 on 2023-01-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
